;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Gameplaycue.Ability.PerfectDodge",NewTagName="Gameplaycue.Ability.PerfectDodge.SlowDown")
+GameplayTagRedirects=(OldTagName="Ability.State.ComboWindow",NewTagName="Ability.State.ComboDuration")
+GameplayTagList=(Tag="Ability.Attack.EnemyAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.ParryAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.ParryAttackSucess",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.PlayerAttack",DevComment="")
+GameplayTagList=(Tag="Ability.ComboCount",DevComment="")
+GameplayTagList=(Tag="Ability.Damage.Enermy",DevComment="")
+GameplayTagList=(Tag="Ability.Damage.Player",DevComment="")
+GameplayTagList=(Tag="Ability.DamageTaken",DevComment="")
+GameplayTagList=(Tag="Ability.DamageTaken.Enermy",DevComment="")
+GameplayTagList=(Tag="Ability.DamageTaken.PLayer",DevComment="")
+GameplayTagList=(Tag="Ability.Death.Enermy",DevComment="")
+GameplayTagList=(Tag="Ability.Death.Player",DevComment="")
+GameplayTagList=(Tag="Ability.Movement.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.State.ComboDuration",DevComment="")
+GameplayTagList=(Tag="Ability.State.DodgeWindow",DevComment="")
+GameplayTagList=(Tag="Ability.State.ParryWindow",DevComment="")
+GameplayTagList=(Tag="Ability.State.PerfectDodgeWindow",DevComment="")
+GameplayTagList=(Tag="Ability.State.Stunning",DevComment="")
+GameplayTagList=(Tag="Ability.State.StunStacking",DevComment="")
+GameplayTagList=(Tag="Ability.Status.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="Ability.Stun.Enermy",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Scale",DevComment="")
+GameplayTagList=(Tag="Event.PerfectDodge.Success",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.Damage.Taken",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.Death.Enermy",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.Death.Player",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.EnermyAttack",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.ParrySuccess",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.PerfectDodge.SlowDown",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Ability.PerfectDodge.SpeedUp",DevComment="")

